[package]
name = "nes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bitflags = "1.3.2"
colored = "2.0.0"
crc = "2.1.0"
env_logger = "0.9.0"
log = "0.4.14"
md5 = "0.7.0"
rand = "0.8.4"
