name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: update apt
        run: sudo apt-get update
      - name: Install libudev
        run: sudo apt-get install -y libudev-dev
      - name: Stable with rustfmt and clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Install cargo-make
        run: cargo install cargo-make --verbose
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
      - name: Run wasm test
        run: cargo make wasm-test
